HttpListener {
    Protocol: HTTP
    Path: ./defaultpath
    Port: 7878
    Host: 127.0.0.1
    Location: / (
        redirect: /http
    )
    Location: favicon.ico (
        redirect: ../favicon.ico
    )
}
HttpsListener {
    Protocol: HTTPS
    Path: ./defaultpath
    Port: 8443
    Host: 127.0.0.1
    Cert: cert/Identity.pem
    Key: cert/leaf_key.pem
    Location: / (
        redirect: /https
    )
    Location: restrict1.html (
        auth: Digest
        name: restrict1@localhost
        user: restrict1
        pass: password
    )
    Location: restrict2.html (
        auth: Digest
        name: restrict2@localhost
        user: restrict2
        pass: password
    )
    Location: restrict3.html (
        auth: Digest
        name: restrict2@localhost
        user: restrict2
        pass: password
    )
    Location: root (
        redirect: ../
        auth: Digest
        name: root
        user: admin
        pass: password
    )
    Location: favicon.ico (
        redirect: ../favicon.ico
    )
}
