HttpListener {
    Protocol: HTTP
    Path: ./defaultpath
    Port: 7878
    Host: 127.0.0.1
    Location: / (
        redirect: http
        auth: Basic
        user: http
        pass: password
    )
    Location: admin (
        auth: Digest
        user: admin
        pass: password
    )
}
HttpsListener {
    Protocol: HTTPS
    Path: ./defaultpath
    Port: 8443
    Host: 127.0.0.1
    Cert: cert/Identity.pem
    Key: cert/leaf_key.pem
    Location: / (
        redirect: https
        auth: Digest
        user: https
        pass: password
    )
    Location: root (
        redirect: ./
    )
    Location: h (
        redirect: http
    )
}