HttpListener {
    Protocol: HTTP
    Path: ./defaultpath
    Port: 7878
    Host: 127.0.0.1
    Cert: cert/Identity.pem
    Key: cert/leaf_key.pem
}
HttpsListener {
    Protocol: HTTPS
    Path: ./defaultpath
    Port: 8443
    Host: 127.0.0.1
    Cert: cert/Identity.pem
    Key: cert/leaf_key.pem
}