[ req ]
distinguished_name  = req_distinguished_name
prompt              = no
x509_extensions     = v3_ca

[ req_distinguished_name ]
countryName             = US
organizationName        = local
commonName              = Leaf

[ v3_ca ]
subjectAltName      = DNS:localhost,IP:127.0.0.1