[ req ]
distinguished_name  = req_distinguished_name
prompt              = no
x509_extensions     = v3_ca

[ req_distinguished_name ]
countryName             = US
organizationName        = local
commonName              = Leaf

[ v3_ca ]
subjectAltName      = IP:127.0.0.1,DNS:localhost,DNS:http.localhost,DNS:https.localhost