#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub enum HttpStatus {
    // 1xx Informational response
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    EarlyHints = 103,

    // 2xx Success
    #[default]
    OK = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritiveInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    IMUsed = 226,

    // 3xx Redirection
    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    UseProxy = 305,
    SwitchProxy = 306,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,

    // 4xx Client Error
    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthenticationRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    ContentTooLarge = 413,
    URITooLong = 414,
    UnsupportedMediaType = 415,
    RangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    ImATeapot = 418,
    MisdirectedRequest = 421,
    UnprocessableContent = 422,
    Locked = 423,
    FailedDependency = 424,
    TooEarly = 425,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    RequestHeaderFieldsTooLarge = 431,
    NoResponse = 444,
    UnavailableForLegalReasons = 451,
    RequestHeaderTooLarge = 494,
    SSLCertificateError = 495,
    SSLCertificateRequired = 496,
    HTTPRequestSentToHTTPSPort = 497,
    ClientClosedRequest = 499,

    // 5xx Server Error
    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    HTTPVersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    BandwidthLimitExceeded = 509,
    NotExtended = 510,
    NetworkAuthenticationRequired = 511,
    WebServerReturnedUnknownError = 520,
    WebServerIsDown = 521,
    ConnectionTimedOut = 522,
    OriginIsUnreachable = 523,
    ATimeoutOccured = 524,
    SSLHandshakeFailed = 525,
    InvalidSSLCertificate = 526,
    OriginUnavailable = 530,
    TemporarilyDisabled = 540,
    NetworkReadTimeoutError = 598,
    NetworkConnectionTimeoutError = 599,

}

impl HttpStatus {
    pub fn from_u16(status: u16) -> Result<HttpStatus, &'static str> {
        match status {
            100 => Ok(HttpStatus::Continue),
            101 => Ok(HttpStatus::SwitchingProtocols),
            102 => Ok(HttpStatus::Processing),
            103 => Ok(HttpStatus::EarlyHints),

            // 2xx Success
            200 => Ok(HttpStatus::OK),
            201 => Ok(HttpStatus::Created),
            202 => Ok(HttpStatus::Accepted),
            203 => Ok(HttpStatus::NonAuthoritiveInformation),
            204 => Ok(HttpStatus::NoContent),
            205 => Ok(HttpStatus::ResetContent),
            206 => Ok(HttpStatus::PartialContent),
            207 => Ok(HttpStatus::MultiStatus),
            208 => Ok(HttpStatus::AlreadyReported),
            226 => Ok(HttpStatus::IMUsed),

            // 3xx Redirection
            300 => Ok(HttpStatus::MultipleChoices),
            301 => Ok(HttpStatus::MovedPermanently),
            302 => Ok(HttpStatus::Found),
            303 => Ok(HttpStatus::SeeOther),
            304 => Ok(HttpStatus::NotModified),
            305 => Ok(HttpStatus::UseProxy),
            306 => Ok(HttpStatus::SwitchProxy),
            307 => Ok(HttpStatus::TemporaryRedirect),
            308 => Ok(HttpStatus::PermanentRedirect),

            // 4xx Client Error
            400 => Ok(HttpStatus::BadRequest),
            401 => Ok(HttpStatus::Unauthorized),
            402 => Ok(HttpStatus::PaymentRequired),
            403 => Ok(HttpStatus::Forbidden),
            404 => Ok(HttpStatus::NotFound),
            405 => Ok(HttpStatus::MethodNotAllowed),
            406 => Ok(HttpStatus::NotAcceptable),
            407 => Ok(HttpStatus::ProxyAuthenticationRequired),
            408 => Ok(HttpStatus::RequestTimeout),
            409 => Ok(HttpStatus::Conflict),
            410 => Ok(HttpStatus::Gone),
            411 => Ok(HttpStatus::LengthRequired),
            412 => Ok(HttpStatus::PreconditionFailed),
            413 => Ok(HttpStatus::ContentTooLarge),
            414 => Ok(HttpStatus::URITooLong),
            415 => Ok(HttpStatus::UnsupportedMediaType),
            416 => Ok(HttpStatus::RangeNotSatisfiable),
            417 => Ok(HttpStatus::ExpectationFailed),
            418 => Ok(HttpStatus::ImATeapot),
            421 => Ok(HttpStatus::MisdirectedRequest),
            422 => Ok(HttpStatus::UnprocessableContent),
            423 => Ok(HttpStatus::Locked),
            424 => Ok(HttpStatus::FailedDependency),
            425 => Ok(HttpStatus::TooEarly),
            426 => Ok(HttpStatus::UpgradeRequired),
            428 => Ok(HttpStatus::PreconditionRequired),
            429 => Ok(HttpStatus::TooManyRequests),
            431 => Ok(HttpStatus::RequestHeaderFieldsTooLarge),
            444 => Ok(HttpStatus::NoResponse),
            451 => Ok(HttpStatus::UnavailableForLegalReasons),
            494 => Ok(HttpStatus::RequestHeaderTooLarge),
            495 => Ok(HttpStatus::SSLCertificateError),
            496 => Ok(HttpStatus::SSLCertificateRequired),
            497 => Ok(HttpStatus::HTTPRequestSentToHTTPSPort),
            499 => Ok(HttpStatus::ClientClosedRequest),

            // 5xx Server Error
            500 => Ok(HttpStatus::InternalServerError),
            501 => Ok(HttpStatus::NotImplemented),
            502 => Ok(HttpStatus::BadGateway),
            503 => Ok(HttpStatus::ServiceUnavailable),
            504 => Ok(HttpStatus::GatewayTimeout),
            505 => Ok(HttpStatus::HTTPVersionNotSupported),
            506 => Ok(HttpStatus::VariantAlsoNegotiates),
            507 => Ok(HttpStatus::InsufficientStorage),
            508 => Ok(HttpStatus::LoopDetected),
            509 => Ok(HttpStatus::BandwidthLimitExceeded),
            510 => Ok(HttpStatus::NotExtended),
            511 => Ok(HttpStatus::NetworkAuthenticationRequired),
            520 => Ok(HttpStatus::WebServerReturnedUnknownError),
            521 => Ok(HttpStatus::WebServerIsDown),
            522 => Ok(HttpStatus::ConnectionTimedOut),
            523 => Ok(HttpStatus::OriginIsUnreachable),
            524 => Ok(HttpStatus::ATimeoutOccured),
            525 => Ok(HttpStatus::SSLHandshakeFailed),
            526 => Ok(HttpStatus::InvalidSSLCertificate),
            530 => Ok(HttpStatus::OriginUnavailable),
            540 => Ok(HttpStatus::TemporarilyDisabled),
            598 => Ok(HttpStatus::NetworkReadTimeoutError),
            599 => Ok(HttpStatus::NetworkConnectionTimeoutError),

            _ => Err("Invalid HTTP status"),
        }
    }

    pub fn to_string(&self) -> &str {
        match self {
            HttpStatus::Continue => "Continue",
            HttpStatus::SwitchingProtocols => "Switching Protocols",
            HttpStatus::Processing => "Processing",
            HttpStatus::EarlyHints => "Early Hints",

            // 2xx Success
            HttpStatus::OK => "OK",
            HttpStatus::Created => "Created",
            HttpStatus::Accepted => "Accepted",
            HttpStatus::NonAuthoritiveInformation => "Non-Authoritive Information",
            HttpStatus::NoContent => "No Content",
            HttpStatus::ResetContent => "Reset Content",
            HttpStatus::PartialContent => "Partial Content",
            HttpStatus::MultiStatus => "Multi-Status",
            HttpStatus::AlreadyReported => "Already Reported",
            HttpStatus::IMUsed => "IM Used",

            // 3xx Redirection
            HttpStatus::MultipleChoices => "Multiple Choices",
            HttpStatus::MovedPermanently => "Moved Permanently",
            HttpStatus::Found => "Found",
            HttpStatus::SeeOther => "See Other",
            HttpStatus::NotModified => "Not Modified",
            HttpStatus::UseProxy => "Use Proxy",
            HttpStatus::SwitchProxy => "Switch Proxy",
            HttpStatus::TemporaryRedirect => "Temporary Redirect",
            HttpStatus::PermanentRedirect => "Permanent Redirect",

            // 4xx Client Error
            HttpStatus::BadRequest => "Bad Request",
            HttpStatus::Unauthorized => "Unauthorized",
            HttpStatus::PaymentRequired => "Payment Required",
            HttpStatus::Forbidden => "Forbidden",
            HttpStatus::NotFound => "Not Found",
            HttpStatus::MethodNotAllowed => "Method Not Allowed",
            HttpStatus::NotAcceptable => "Not Acceptable",
            HttpStatus::ProxyAuthenticationRequired => "Proxy Authentication Required",
            HttpStatus::RequestTimeout => "Request Timeout",
            HttpStatus::Conflict => "Conflict",
            HttpStatus::Gone => "Gone",
            HttpStatus::LengthRequired => "Length Required",
            HttpStatus::PreconditionFailed => "Precondition Failed",
            HttpStatus::ContentTooLarge => "Content Too Large",
            HttpStatus::URITooLong => "URI Too Long",
            HttpStatus::UnsupportedMediaType => "Unsupported Media Type",
            HttpStatus::RangeNotSatisfiable => "Range Not Satisfiable",
            HttpStatus::ExpectationFailed => "Expectation Failed",
            HttpStatus::ImATeapot => "I'm A Teapot",
            HttpStatus::MisdirectedRequest => "Misdirected Request",
            HttpStatus::UnprocessableContent => "Unprocessable Content",
            HttpStatus::Locked => "Locked",
            HttpStatus::FailedDependency => "Failed Dependency",
            HttpStatus::TooEarly => "Too Early",
            HttpStatus::UpgradeRequired => "Upgrade Required",
            HttpStatus::PreconditionRequired => "Precondition Required",
            HttpStatus::TooManyRequests => "Too Many Requests",
            HttpStatus::RequestHeaderFieldsTooLarge => "Request Header Fields Too Large",
            HttpStatus::NoResponse => "No Response",
            HttpStatus::UnavailableForLegalReasons => "Unavailable For Legal Reasons",
            HttpStatus::RequestHeaderTooLarge => "Request Header Too Large",
            HttpStatus::SSLCertificateError => "SSL Certificate Error",
            HttpStatus::SSLCertificateRequired => "SSL Certificate Required",
            HttpStatus::HTTPRequestSentToHTTPSPort => "HTTP Request Sent To HTTPS Port",
            HttpStatus::ClientClosedRequest => "Client Closed Request",

            // 5xx Server Error
            HttpStatus::InternalServerError => "Internal Server Error",
            HttpStatus::NotImplemented => "Not Implemented",
            HttpStatus::BadGateway => "Bad Gateway",
            HttpStatus::ServiceUnavailable => "Service Unavailable",
            HttpStatus::GatewayTimeout => "Gateway Timeout",
            HttpStatus::HTTPVersionNotSupported => "HTTP Version Not Supported",
            HttpStatus::VariantAlsoNegotiates => "Variant Also Negotiates",
            HttpStatus::InsufficientStorage => "Insufficient Storage",
            HttpStatus::LoopDetected => "Loop Detected",
            HttpStatus::BandwidthLimitExceeded => "Bandwidth Limit Exceeded",
            HttpStatus::NotExtended => "Not Extended",
            HttpStatus::NetworkAuthenticationRequired => "Network AuthenticationR equired",
            HttpStatus::WebServerReturnedUnknownError => "Web Server Returned Unknown Error",
            HttpStatus::WebServerIsDown => "Web Server Is Down",
            HttpStatus::ConnectionTimedOut => "Connection Timed Out",
            HttpStatus::OriginIsUnreachable => "Origin Is Unreachable",
            HttpStatus::ATimeoutOccured => "A Timeout Occured",
            HttpStatus::SSLHandshakeFailed => "SSL Handshake Failed",
            HttpStatus::InvalidSSLCertificate => "Invalid SSL Certificate",
            HttpStatus::OriginUnavailable => "Origin Unavailable",
            HttpStatus::TemporarilyDisabled => "Temporarily Disabled",
            HttpStatus::NetworkReadTimeoutError => "Network Read Timeout Error",
            HttpStatus::NetworkConnectionTimeoutError => "Network Connection Timeout Error",
        }
    }
}